// <auto-generated />
namespace RevenueAndExpense.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AllEntities_7Mar2020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllEntities_7Mar2020));
        
        string IMigrationMetadata.Id
        {
            get { return "202003070819399_AllEntities_7-Mar-2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
